<a href="https://colab.research.google.com/github/guebin/DL2025/blob/main/posts/01wk-1.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" style="text-align: left"></a>

# 1. 강의영상

{{<video https://youtu.be/playlist?list=PLQqh36zP38-w2wjg7vQJHPP89wWGSq-MZ&si=J0lxSPEePOD-5BOL >}}

# 2. Imports

In [1]:
import torch

# 3. 환경셋팅 

`-` 코랩이용자: 별도의 설치 필요 없음 

- GPU 관리가 꼭 필요함!! (시험하루전날 수업 몰아서 듣지않기, 아이디만들어두기)
- 특히 시험기간에 조심하세요 

`-` 리눅스서버 사용자 (ref: <https://pytorch.org/get-started/locally/>)

```bash
conda create -n dl2025 python=3.9
conda activate dl2025 
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126
```

# 4. 필요한 지식 

`-` 선형대수학

- 벡터와 행렬
- 행렬의 곱셉
- 트랜스포즈

`-` 기초통계학(수리통계)

- 정규분포, 이항분포
- 모수, 추정
- $X_i \overset{i.i.d.}{\sim} N(0,1)$


`-` 회귀분석 

- 독립변수($y$), 설명변수($X$)
- ${\boldsymbol y} = {\bf X}{\boldsymbol \beta} + {\boldsymbol \epsilon}$

`-` 파이썬

- 파이썬 기본문법
- 넘파이, 판다스
- 전반적인 클래스 지식 (`__init__`, `self`, ...)
- 상속

# 5. 파이토치 기본

## A. torch 

`-` 벡터

In [2]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

`-` 벡터의 덧셈

In [5]:
torch.tensor([1,2,3]) + torch.tensor([2,2,2])

tensor([3, 4, 5])

`-` 브로드캐스팅 

In [6]:
torch.tensor([1,2,3]) + 2

tensor([3, 4, 5])

## B. 벡터와 매트릭스 

`-` $3 \times 2$ matrix

In [9]:
torch.tensor([[1,2],[3,4],[5,6]]) 

tensor([[1, 2],
        [3, 4],
        [5, 6]])

`-` $3 \times 1$ matrix = $3 \times 1$ column vector

In [13]:
torch.tensor([[1],[3],[5]]) 

tensor([[1],
        [3],
        [5]])

`-` $1 \times 2$ matrix = $1 \times 2$ row vector

In [14]:
torch.tensor([[1,2]]) 

tensor([[1, 2]])

`-` 더하기 

***브로드캐스팅(편한거)***

In [15]:
torch.tensor([[1,2],[3,4],[5,6]]) - 1

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [17]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([[-1],[-3],[-5]])

tensor([[0, 1],
        [0, 1],
        [0, 1]])

In [19]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([[-1,-2]])

tensor([[0, 0],
        [2, 2],
        [4, 4]])

***잘못된 브로드캐스팅***

In [21]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([[-1,-3,-5]])

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [22]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([[-1],[-2]])

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

***이상한 것***

In [25]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([-1,-2])

tensor([[0, 0],
        [2, 2],
        [4, 4]])

In [26]:
torch.tensor([[1,2],[3,4],[5,6]]) + torch.tensor([-1,-3,-5])

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

`-` 행렬곱

***정상적인 행렬곱***

In [27]:
torch.tensor([[1,2],[3,4],[5,6]]) @ torch.tensor([[1],[2]])

tensor([[ 5],
        [11],
        [17]])

In [28]:
torch.tensor([[1,2,3]]) @ torch.tensor([[1,2],[3,4],[5,6]]) 

tensor([[22, 28]])

***잘못된 행렬곱***

In [29]:
torch.tensor([[1,2],[3,4],[5,6]]) @ torch.tensor([[1,2]])

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 1x2)

In [30]:
torch.tensor([[1],[2],[3]]) @ torch.tensor([[1,2],[3,4],[5,6]]) 

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x1 and 3x2)

***이상한 것***

In [31]:
torch.tensor([[1,2],[3,4],[5,6]]) @ torch.tensor([1,2]) # 이게 왜 가능..

tensor([ 5, 11, 17])

In [35]:
torch.tensor([1,2,3]) @ torch.tensor([[1,2],[3,4],[5,6]]) # 이건 왜 가능?

tensor([22, 28])

## C. transpose, reshape

`-` transpose 

In [157]:
torch.tensor([[1,2],[3,4]]).T 

tensor([[1, 3],
        [2, 4]])

In [158]:
torch.tensor([[1],[3]]).T 

tensor([[1, 3]])

In [160]:
torch.tensor([[1,2]]).T 

tensor([[1],
        [2]])

`-` reshape

***일반적인 사용***

In [42]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(2,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [43]:
torch.tensor([[1,2],[3,4],[5,6]])

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [44]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(1,6)

tensor([[1, 2, 3, 4, 5, 6]])

In [45]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(6)

tensor([1, 2, 3, 4, 5, 6])

***편한 것***

In [49]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(2,-1)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [50]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(6,-1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [51]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(-1,6)

tensor([[1, 2, 3, 4, 5, 6]])

In [52]:
torch.tensor([[1,2],[3,4],[5,6]]).reshape(-1)

tensor([1, 2, 3, 4, 5, 6])

## D. concat, stack $(\star\star\star)$

`-` concat 

In [53]:
a = torch.tensor([[1],[3],[5]])
b = torch.tensor([[2],[4],[6]])
torch.concat([a,b],axis=1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [59]:
torch.concat([a,b],axis=1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

`-` stack

In [60]:
a = torch.tensor([1,3,5])
b = torch.tensor([2,4,6])
torch.stack([a,b],axis=1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [69]:
torch.concat([a.reshape(3,1),b.reshape(3,1)],axis=1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

:::{.callout-warning}

concat과 stack을 지금 처음본다면 아래를 복습하시는게 좋습니다. 

<https://guebin.github.io/PP2024/posts/06wk-2.html#numpy와-축axis>
:::